### ISSUE TITLE
Swap vs. zram

### ISSUE THREAD

**Issue by JohnnyricoMC** [Telraam/Telraam-RPi#1]
/Misc/general-configuration-HOWTO.txt suggests a 100MB swapfile is created on the SD-card. Using flash-based storage for swap is bad for the device's lifespan and when used on an SD-card (which generally has poor random write performance) can lead to excessive CPU I/O wait, causing a performance loss during memory-intensive tasks.

If available memory is more important than CPU performance for Telraam, an alternative could be to use memory compression. This would be faster than writing the memory to a swapfile on the SD-card.

The Linux kernel supports the use of [zram](https://en.wikipedia.org/wiki/Zram) to this end: part of the RAM is used to create a block device, but with compression. This block device can then be used as swap area (or a general purpose ramdisk). Essentially, it claims part of the RAM to present as a disk but compresses all data written to the disk.

See also:
https://html.dynu.net/index.php/increase-ram-zram/  and https://hackaday.io/project/29898-boost-your-raspberry-pi-in-minutes/details under the "Overclocking with ZRAM" section (despite the title, this section really only concerns zram, not overclocking). These articles make use of Novaspirit's zram script: https://github.com/novaspirit/rpi_zram .

**Comment by smaerivo** [comment]
Hi, thank you for your comment and suggestion; we are aware that flash-based storage isn't the best for swap. However this is not an issue in the case of Telraam, as swap-memory is not accessed during operations. It was only used when compiling the OpenCV library (and in that case, the Pi's available RAM capacity would certainly not be enough to sacrifice it in favour of zram). Current memory requirements are more than sufficient, and any memory leaks on the longer term are handled by the Telraam automatically rebooting itself every night.
