### ISSUE TITLE
Telramian install script

### ISSUE THREAD

**Issue by ArdescoConsulting** [Telraam/Telraam-RPi#10]
Hi,

I like my installs automatic so I turned the installation instructions into an installation script called telramian

https://github.com/ArdescoConsulting/Telramian

It uses Raspbian Buster lite, opencv 4.1.2 and python 4.7.3.

It only requires a small change in telraam_monitoring.py

In OpenCV 3 findContours returns 3 values and in OpenCV 4 only two. The third is not used anyway so no problem.

telraam_monitoring.py can be used with both OpenCV versions with the change below

Replace 
```python
im2, contours, hierarchy = cv2.findContours with contours, hierarchy = cv2.findContours
```
with
```python
if cv2.__version__.startswith('4'):
	contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)  # Find contours (find the circumference of the objects)
else:
	im2, contours, hierarchy = cv2.findContours(thresh1, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)  # Find contours (find the circumference of the objects)
```

The telramian.py script uses a temp fix of telraam_monitoring.py until the above change is made at the source.
```python
#temp fix
# the original telraam script is for opencv 3 while we are using opencv 4
# the difference is that findContours is now returning 2 values instead of 3
# no worries because the 3rd values was not used anayway
# so just replace im2, contours, hierarchy = cv2.findContours with contours, hierarchy = cv2.findContours
# until this is fixed in the original script
sed -i 's/im2, contours, hierarchy = cv2.findContours/contours, hierarchy = cv2.findContours/g' $PATH_TELRAAM_SCRIPTS/telraam_monitoring.py
#temp fix

```
I ran the script on my RPi 4 GB to shorten the build time and then placed the SD in my RPi 3 telraam.

Enjoy while you let the computer do your building 😊

**Comment by Telraam** [comment]
Very nice!

**Comment by ShamalHPW** [comment]
@ArdescoConsulting  - This is awesome. 
Will Telraam now work on the RPI4? Currently the standard install won't boot :(

**Comment by ArdescoConsulting** [comment]
@ShamalHPW
I have just updated the script with the latest security enhancements, software updates and various smaller changes. The readme.md is also simplified.
It is running on my RPI4 with 4 GB and RPI3B without problems.

**Comment by Telraam** [comment]
Hello,

We will add the check for the opencv version to our new image, being released shortly.

Br

**Comment by kilnageer2** [comment]
Hi. I've been trying to get Telgaam going for the last few days. First with the published telraam-sd-image.zip image on a RPi Zero W (could not see camera images) then using the [step-by-step guide](https://github.com/Telraam/Telraam-RPi/blob/master/Misc/general-configuration-HOWTO.txt). First on a RPi 4 64-bit (picamera issues) followed by a 32-bit OS (opencv and http issues). Finally, I tried using @ArdescoConsulting  script but had mysql-connect and http issues. These wre resolved with "(sudo) pip3 install mysql-connect" and copying over all the /var/www/html files from the original telraam-sd-image.zip image.

So I have finally got my Dashboard to display "Telraam is counting Last data package received on 2021-02-07 19:11" and the RPi 4 working. Hopefully count data will arrive in a few days.

So, thanks everybody and I'm really looking forward to moving my opencv knowledge on and providing some citizen science data from here in the West of Ireland :) (Might try counting the planes at Shannon Airport next!)

**Comment by Telraam** [comment]
> So, thanks everybody and I'm really looking forward to moving my opencv knowledge on and providing some citizen science data from here in the West of Ireland :) (Might try counting the planes at Shannon Airport next!)

Glad to hear that you managed to get started, keep us updated!
