### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by MathiasVDA** [Telraam/Telraam-RPi#12]
Hello, 

First of all, thank you for this wonderful and valuable idea. I think it's a great way to help make better decisions!

Secondly, I have some issues/concerns with the security point of view for this project. I am by no means a security expert or a foolproof example either. But I feel obliged to voice my concerns. As I understand it, the raspbian image you advise to load on a pi:
- Has a default superuser username/password combination
- Is suppose to be connected to peoples wifi network, on which also other devices are connected. Thus granting access to those other network devices 
- Executes a daily python script that it downloads from your site and executes it with sudo rights

I see a number of ways in which this can go wrong. What if your servers are hacked and a bad script is spread to all the hosts? Or if people gain access to the network and with the default user have unlimited access to the device?

I hope I am wrong and I overlooked something...

If not, I would advise:
- to ask the user for a new password for the 'pi' user (for example on the first page, besides asking for the wifi login, also ask the user to enter a new password for 'pi') 
- to revise the update strategy and not need sudo rights for daily updates
- Advise users to put the pi on a guest network that only has outgoing internet access and not access to other clients on the network.

Why does samba needs to be active?

**Comment by pagaille** [comment]
Agreed ! For me the most problematic part is the third point. 

Security looks largely overlooked in this project. 

I remember I had to contact someone at telraam because his mailer account password (and others) was directly visible on a (not disabled) debug page on the live website !

Matthieu G.  (en mode mobile)

**Comment by Jefwillems** [comment]
This is a major issue and no-one at @Telraam cares enough to answer.

**Comment by Telraam** [comment]
One of our top priorities in the undergoing development phase is solving these security related issues. As always we are grateful for all of you for pointing out weak points in our setup, and we encourage you to continue to do so in the future too. On the other hand we need to ask some time, we are very busy on multiple fronts, we are also working on making our whole back-end side more secure and robust, which is a large project on its own. Thank you for your patience!

**Comment by Telraam** [comment]
Please see our update over the security issues here: https://github.com/Telraam/Telraam-RPi/issues/16
