### ISSUE TITLE
Reinstall over ssh

### ISSUE THREAD

**Issue by mclaeysb** [Telraam/Telraam-RPi#15]
Hi

My Telraam (1003073462) has been down for a couple of days now. Connecting to it's WiFi I checked that the camera works fine. The FAQ page now directs me to reinstall the firmware, but I don't have a SD card-reader available. Is it possible to do this over ssh? I found a mention of ssh in the docs but I couldn't find sufficient information to even login.

Otherwise, is this possible reinstall in another way that does not require a reader?

Kind regards
Manuel

**Comment by Telraam** [comment]
Dear Manuel,

Please submit the problem at https://telraam.zendesk.com/hc/en-be/requests/new there we will try to help you as soon as possible.

Best regards,
The Telraam Team
