### ISSUE TITLE
Telraam on Pi Zero W ?

### ISSUE THREAD

**Issue by mxagat** [Telraam/Telraam-RPi#17]
Dear Telraam team,

Would Telraam work fine on Pi zero W, with the standard (or IR) Pi camera ? It is quite cheaper than the Pi3 while having 512 RAM.

Cheers

**Comment by Telraam** [comment]
Hello,

Thanks for your question!

We did not test this ourselves, but we think the Pi zero W does not have enough cpu power to work at acceptable framerates.

Cheers

**Comment by mxagat** [comment]
Thanks for the reply. It makes sense.  I'll give it a try just for sport and see how it goes (erroneous count ? Lag ? crash ?)
Anyways, thank you for this exciting citizen science project.

**Comment by harleyday** [comment]
I've just put a Telraam together using a pi zero, and it (seems) to be working. I'm getting some numbers in the telraam website, but I don't know how accurate they are at this stage. Maybe next weekend I'll try manually counting for a few hours to see how well the data reflects reality.

**Comment by redmond2742** [comment]
Any updates on running this on a RPi Zero? I am curious of the steps you took to install the software and if they were typical? Thank you.

**Comment by Peterjbdk** [comment]
@harleyday Would you be able to set out the steps that you followed to get a Pi Zero W working? I am trying and failing!
