### ISSUE TITLE
Support for unofficial raspi-cam

### ISSUE THREAD

**Issue by ruudvddries** [Telraam/Telraam-RPi#19]
I have a few redundant Chinees raspberry pi camera's. These do nog work with telraam. Is that as expected? Or are both my camera's 'dead'? Or is only the official camera supported?

**Comment by Telraam** [comment]
Hello,

Only the official camera is supported with our sd card image.
It might be possible to make it work with a unofficial camera, but you would have to look into the code yourself.
Also keep in mind that our nightly updates may break your modifications.

Br
