### ISSUE TITLE
Support older RPi's (RPi 2b?) with wifi dongle?

### ISSUE THREAD

**Issue by alpha-coffeehacker** [Telraam/Telraam-RPi#20]
Is it possible to use the telraam software with older RPi's in combination with a USB-wifi dongle? I tried but the telraam-AP is visible (tried 2 different dongles), but I can't connect to it (neither with android10 device, nor with W10-laptop/Ipad). With Ipad (IOS13.4.1) I get 'wrong password'.

**Comment by Telraam** [comment]
Hello,

Our image is not tested with RPi 2b.
It might be possible to get it working, but you will have to look into the code.

I know someone has tweaked the telraam code to work with an ethernet connection, so a wifi dongle should be possible as well.

Br

**Comment by dvanderfaeillie** [comment]
@alpha-coffeehacker I'm runnig telraam it on an RPi 1B. It runs ok, average load is a bit above 1 though...

I flashed the dev image, and added the ssh file to enable ssh access. I also edited the `/etc/network/interfaces` with my `wlan0` settings. I think I stopped the `telraam_ap_control_loop` service to maintain it in permanent *monitoring* mode.

**Comment by alpha-coffeehacker** [comment]
@dvanderfaeillie : thanx, will try this!

**Comment by dvanderfaeillie** [comment]
@alpha-coffeehacker Perhaps I should consider writing a step by step tutorial 🙂️, I'm also considering writing this for other sbc's as well. (There is [Telramian](https://github.com/ArdescoConsulting/Telramian) though)

**Comment by poolsztynsku** [comment]
@dvanderfaeillie Hi. Did you have the opportunity to test out other sbcs?

**Comment by dvanderfaeillie** [comment]
> @dvanderfaeillie Hi. Did you have the opportunity to test out other sbcs?

Sorry @poolsztynsku, I didn't... (lack of time and of sbc's...) Have you got an SBC+camera you would like to use for a test?

**Comment by poolsztynsku** [comment]
@dvanderfaeillie Hi. Thanks for a reply. Due to no infos I could find I've got RPi Zero W bundle (found a post about successful installation) and unfortunately now have some issues with stable WiFi/Telraam server connection. Hacking in progress as this seems to be known issue... Would read about your RPi 1B hacking.
