### ISSUE TITLE
Using MySql when not needed

### ISSUE THREAD

**Issue by jfisbein** [Telraam/Telraam-RPi#22]
in Access%20point/setup/index.php MySQL is used to store the WiFi credentials and one configuration value in `settings`.

Being limited on RAM and knowing that MySQL consumes lot of RAM I think it would make lot of sense to stop using MySQL, and simply use some files (yaml, json, etc) to store that information.

P.S: For WiFi credentials you can use wpa_suplicant.

**Comment by Telraam** [comment]
In the v11 image version, we moved from mysql to json files.
