### ISSUE TITLE
Speed counting rasp pi 3 < 4 ?

### ISSUE THREAD

**Issue by Rinlinius** [Telraam/Telraam-RPi#25]
Hello,
I see it is possible to run telraam on rasp pi 4. Just need to figure out what I need to change.
But I wonder if Telraam would count faster if I run the image on a pi 4? Because when its image processing it is not counting if I read it correctly. So if I run this images in a crowded area would the 4 be more accurate ?

**Comment by Telraam** [comment]
Hello,

It is possible that the pi4 is more accurate.
More power will result into less time being spent on image processing.

We do not support the pi4 ourselves, but take a look at https://github.com/ArdescoConsulting/Telramian

Best regards
