### ISSUE TITLE
WLAN access point with default credentials is available indefinitely

### ISSUE THREAD

**Issue by behrisch** [Telraam/Telraam-RPi#30]
Whenever the Telraam device disconnects from its WLAN it creates an access point for reconnecting which keeps running until you connect. While this is in principle a good idea, it opens a security hole because the credentials for connecting are the default ones and cannot be changed so everyone can connect to the device and gets immediate access to the camera. An easy "fix" would be to limit the amount of time the access point keeps running to some minutes and require the user to power cycle the device to enable access point again. It would be even better if the user would be required to (or at least could) change the password for the access point.

**Comment by Telraam** [comment]
Hello,

We will keep this in mind when we create a new software image for the telraam devices.
Thanks for your comment!

Best regards
