### ISSUE TITLE
NoIR camera V2 compatibility

### ISSUE THREAD

**Issue by joakimfors** [Telraam/Telraam-RPi#31]
The "normal" camera module is out of stock almost everywhere. I wonder if it is possible to use the NoIR version. The sensor and lens is the same but I guess the image it produces, especially at dusk, is quite different and I don't know if the classification algorithm handles this correctly.

**Comment by Telraam** [comment]
Hello,

We did not test this ourselves.
We would think this will work, maybe with slightly different results.

So you would have to try it out yourself.

Best regards
