### ISSUE TITLE
Connect Telraam with LAN instead of WLAN

### ISSUE THREAD

**Issue by coenist** [Telraam/Telraam-RPi#32]
Dear colleagues,
We are aiming at the installation of a series of Telraam-devices at our higher education campus in Belgium. As we are using EDUROAM here, a wireless connection does not seem to be possible. Thanks to the availability of the telraam-dev-image, we have been able to connect the Raspberry to a wired network, and the system is online and connected with the internet. Unfortunately, the data are not sent to the Telraam servers. Motivated by the remark made by @mrtnrey (#16, "I use the access to tweak my telraam to connect to my LAN instead of WLAN, with a USB-to-RJ45 dongle"), we would like to use the system in a similar way.
My question is therefore if one of you would be so kind to guide us in the right direction to broadcast the data via LAN instead of WLAN?
Many thanks!

**Comment by mrtnrey** [comment]
Hi, I made a gist for that: https://gist.github.com/mrtnrey/4a46b70755572ee74006a9e48cb78691
Some (minimal) experience in Linux is required, but I hope it will help. Good luck!

**Comment by Telraam** [comment]
Hi mrtnrey,

Thank you for the list you made.
Everything seems to be in the list to make lan working.

Telraam

**Comment by MartenBE** [comment]
@Telraam in order to connect the pi to the eduroam network, we need to be able to use the following wifi settings:
![Screenshot_20220523_171022](https://user-images.githubusercontent.com/1958780/169851080-cbba0c17-7faa-4b0d-b73c-38838a5fd875.png)
As it is possible to set this connection up on any Linux distro, I was wondering if it is possible to set this connection up on the Telraam dev image (which is Raspbian) without breaking the networking scripts?
See https://inrg.soe.ucsc.edu/howto-connect-raspberry-to-eduroam/ for a tutorial on the cli.

**Comment by Telraam** [comment]
Hi,

We did not test this ourselves, but it should work.

You would have to modify the networking script:
/home/pi/Telraam/Scripts/telraam_ap_control_loop.py

This script will otherwise overwrite the wpa_supplicant file and break the eap connection.

Best regards

**Comment by MartenBE** [comment]
If we flash the telraam device with Raspbian 11, we can connect with eduroam without any problems. When using the official image (on raspbian 9) it is not functional. Thus outdated packages prevent us from connecting to the eduroam network. Would it be possible to rebase the dev image to raspbian 11? This would probably solve our issues

**Comment by Telraam** [comment]
Hi,

Unfortunately cannot rebase the dev image to raspbian 11.

But you could try building the telraam image yourselve, starting from raspian 11.
This is a 3rd party script that installs the telraam software: https://github.com/ArdescoConsulting/Telramian
We do not maintain this, but it might help you get started with building the image.

Best regards

**Comment by MartenBE** [comment]
The building of the image with basic monitoring on Raspbian 11 was actually easier than expected as we don't need the network or update service, only the monitoring service:

1. Install the latest Raspbian Lite on the raspberry pi (Raspbian 11 in our case).
2. Use `$ sudo raspi-config` to ...
    * Set the correct timezone
    * Enable the camera
3. Enable `wlan0` by `$ rfkill unblock wlan0`.
4. Edit `/etc/wpa_supplicant/wpa_supplicant.conf` with the contents for your internet connection (eduroam in our case).
5. Edit `/etc/network/interfaces`:
    ```
    auto wlan0
    iface wlan0 inet dhcp
    wpa_conf /etc/wpa_supplicant/wpa_supplicant.conf
    ```
6. Pull this repository by `$ git clone https://github.com/Telraam/Telraam-RPi ~/Telraam` .
7. Install the necessary dependencies:
    ```
    $ apt update
    $ apt install python3-numpy python3-opencv python3-pandas
    ```
8. Change the field `ExecStart` in `~/Telraam/Image processing/telraam_monitoring.service` to `/usr/bin/python3 /home/pi/Telraam/Image processing/telraam_monitoring.py --idandtrack` .
9. Install the service and enable:
    ```
    $ cd ~/Telraam/Image processing/
    $ sudo systemctl link "$PWD/telraam_monitoring.service"
    $ sudo systemctl enable --now telraam_monitoring.service
    ```
10. Optional:
    * Change the password of the `pi` user
    * Enable SSH
    * Check the device ID, this is the decimal value of the MAC address without hyphens (obtained by `python3 ~/Telraam/Misc/telraam_show_mac_address.py`).
