### ISSUE TITLE
Support for Raspberry pi 4

### ISSUE THREAD

**Issue by rubenwouters1990** [Telraam/Telraam-RPi#33]
Is there a version of Telraam available that works with the raspberry pi 4?

**Comment by Telraam** [comment]
Hi Ruben,

There is no version of Telraam that is working with a rapberry pi 4.

There is a third party that made an install script for pi 4:
https://github.com/ArdescoConsulting/Telramian

You could take a look at that, but we have not tested this script ourselves.

Best regards
