### ISSUE TITLE
Can't login to raspberrypi image

### ISSUE THREAD

**Issue by marcovanwoudenberg** [Telraam/Telraam-RPi#35]
After booting the device there appears a login prompt on my pi.
login: pi
password: pi

doesnt work. I read that there was an security update about some issues with a random password but this should have been fixed in the latest release. I'm using the following image: telraam-image-v11c.img - dated 2-6-2022 can anybody advice what going on?

Thank you very much. Kind regards.

**Comment by Telraam** [comment]
Hi Marco,

If you want to login on the telraam, you should use the dev image.
The normal image doesn't let you log in.

You can find more information on the dev image at:
https://github.com/Telraam/Telraam-RPi/blob/master/telraam-dev-image

Best regards
