### ISSUE TITLE
Connection refused camera stream

### ISSUE THREAD

**Issue by marcovanwoudenberg** [Telraam/Telraam-RPi#36]
Hi,

After booting my device and setting it up. On the camera page is see that the connection for the camera stream is refused. 

I think this is because the ip it uses is the same as my router login page. Which requires a password and there for blocks the stream from starting.

What can I do to fix this?

Kr,
Marco

**Comment by Telraam** [comment]
Hi,

The camera is not available when the device is counting traffic.  It's then being used by the script that does the counting.
So I think this what you are seeing after setting up the device.

Kr
