### ISSUE TITLE
[Website] Link to github redirects via facebook

### ISSUE THREAD

**Issue by pietervdvn** [Telraam/Telraam-RPi#8]
Hey guys,

[This page](https://telraam.zendesk.com/hc/nl/articles/360026945851-Meewerken-aan-Telraam-GitHub) on the FAQ has a link to this github, but clicking it gives a facebook message 'Warning - leaving facebook'.

Perhaps this should be fixed?

**Comment by Telraam** [comment]
Thank you for noting, we have checked and the link was redirecting via Facebook. We fixed it.
