### ISSUE TITLE
Support registration from non-raspberry pi HW

### ISSUE THREAD

**Issue by ginovh** [Telraam/Telraam-RPi#9]
One could run the telraam_monitoring.py script on other hardware. E.g. with some minor modifications I could run it on i3/ubuntu 18.04 + logitech C510 webcam. (Any OS/HW that supports openCV and python should work.) If one is allowed to just register it's MAC address with a street, people with other HW could also contribute to telraam?

**Comment by Telraam** [comment]
That is entirely possible. However, as we are going to deploy to a broader public, we will not support this officially. The main reason is that there currently is a tight coupling between the software (contour detection) and the hardware (camera), which we cannot guarantee to remain working when switching to other devices. It would require extra tuning and lots of testing to make sure the results would be comparable to the ones we already have now. In addition, we would need to be able to flag in our back-end that the data is coming from a non-standard Telraam. So we strongly advise against this approach.
